# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-development.txt
    - name: Lint with pylint
      run: |
        pip install pylint
        python -m pylint app/* -E 
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Check black formatting
      run: |
        pip install black
        python -m black app/ --check
